Add the option to define a port, username and password in the config.yaml
stjohnjohnson/mqtt-dasher pull request #3
Opened 2017-09-11 20:37 UTC by nielstron

I just set the parsed settings from the config.yaml as object as `options` to [mqtt.connect](https://www.npmjs.com/package/mqtt#connect). By adding username, password and port those settings can be changed. [Accepted values](https://www.npmjs.com/package/mqtt#mqttclientstreambuilder-options) will apply.

2017-09-11 23:30 UTC, stjohnjohnson requested changes
Looks very good.  Can you just fix the spacing please?

2017-09-11 23:30 UTC, stjohnjohnson commented on server.js
> +		var mqtt_broker_options = config.mqtt;
Looks like you're missing indentation here.

2017-09-12 18:54 UTC, nielstron commented
So yeah the indentation should be fixed now

2017-09-15 05:44 UTC, stjohnjohnson approved these changes

2017-09-15 05:45 UTC, merged

2017-09-15 05:45 UTC, stjohnjohnson commented
Thanks!